registry:
  restart: always
  container_name: docker-registry
  image: registry:2
  privileged: true
  network_mode: host
  environment:
    REGISTRY_HTTP_SECRET: password
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker.hubao-tech.com.pem
    REGISTRY_HTTP_TLS_KEY: /certs/docker.hubao-tech.com.key
  volumes:
    - /opt/registry/data:/var/lib/registry
    - /opt/nginx/cert:/certs
    - /opt/registry/auth:/auth